-- Your SQL goes here
CREATE TABLE wallet (
	id SERIAL PRIMARY KEY,
	user_id INT NOT NULL,
	balance DECIMAL(10, 2) NOT NULL CHECK (balance >= 0),
	status BOOL NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);
